[deps]
Agents = "46ada45e-f475-11e8-01d0-f70cc89e6671"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
GraphPlot = "a2cc645c-3eea-5389-862e-a155d0052231"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
ImageMagick = "6218d12a-5da1-5696-b52f-db25d2ecc6d1"
InteractiveDynamics = "ec714cd0-5f51-11eb-0b6e-452e7367ff84"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
QuartzImageIO = "dca85d43-d64c-5e67-8c65-017450d5d020"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
